# Use an official Node.js runtime as the base image
FROM node:22-alpine AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock) first to leverage Docker caching
COPY ./package*.json ./   
COPY ./packages/shared/package*.json ./packages/shared/   
COPY ./apps/backend/package*.json ./apps/backend/

#Copy the root ts-config file
COPY ./tsconfig.json ./

# Copy ts-config file
COPY ./apps/backend/tsconfig.json ./apps/backend/

# Install dependencies
RUN npm ci 

# Copy the rest of the application files
COPY ./packages/shared ./packages/shared
COPY ./apps/backend ./apps/backend

# Compile TypeScript to JavaScript
RUN npm run build --workspace=@campusly/backend

# Expose the application's port
EXPOSE 3000

FROM node:22-alpine AS production

WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock) first to leverage Docker caching
COPY ./package*.json ./   
COPY ./packages/shared/package*.json ./packages/shared/   
COPY ./apps/backend/package*.json ./apps/backend/

COPY ./packages/shared ./packages/shared

COPY --from=build /app/apps/backend/dist ./apps/backend/dist

RUN npm ci --omit=dev

# Command to start the application
CMD ["npm", "start" , "--workspace=@campusly/backend"]