// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
import { defineConfig } from "prisma/config";
import dotenv from "dotenv";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const currentDirectory = dirname(fileURLToPath(import.meta.url));

dotenv.config({
  path: [
    join(currentDirectory, ".env.dev"),
    join(currentDirectory, ".env.prod"),
  ],
  override: true,
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      process.env["DATABASE_URL"] ??
      (() => {
        throw new Error("Environment variable DATABASE_URL not found.");
      })(),
  },
});
