export enum ErrorMachineCode {
  // General
  INTERNAL_ERROR = "INTERNAL_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INVALID_REQUEST = "INVALID_REQUEST",

  // Authentication
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  UID_NOT_FOUND = "UID_NOT_FOUND",

  // Authorization
  FORBIDDEN = "FORBIDDEN",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",

  // User
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",

  // Validation
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_EMAIL = "INVALID_EMAIL",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_IMAGE_MIME_TYPE = "INVALID_IMAGE_MIME_TYPE",
  FILE_NOT_FOUND = "FILE_NOT_FOUND",
  IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND",

  // Resource
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS",

  // Database
  DATABASE_ERROR = "DATABASE_ERROR",
  DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR",

  // External services
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
  FIREBASE_ERROR = "FIREBASE_ERROR",

  // Profile
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",
  PROFILE_ALREADY_EXISTS = "PROFILE_ALREADY_EXISTS",

  // Club
  CLUB_NOT_FOUND = "CLUB_NOT_FOUND",
  CLUB_ALREADY_EXISTS = "CLUB_ALREADY_EXISTS",
}
