import "@src/load-env.js";

import { prisma } from "@src/lib/prisma.js";

import { v4 as uuidv4 } from "uuid";

const tagNames = [
  // Academic & Science
  "Computer Science",
  "Software Engineering",
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
  "Cybersecurity",
  "Robotics",
  "Electronics",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Mechatronics",
  "Industrial Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Biomedical Engineering",
  "Architecture",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Genetics",
  "Medicine",
  "Dentistry",
  "Pharmacy",
  "Psychology",
  "Sociology",
  "Philosophy",
  "History",
  "Geography",
  "Law",
  "Economics",
  "Business",
  "Finance",
  "Marketing",
  "Political Science",
  "International Relations",
  "Astronomy",
  "Neuroscience",
  "Environmental Science",

  // Technology
  "Technology",
  "Programming",
  "Web Development",
  "Mobile Development",
  "Game Development",
  "Cloud Computing",
  "DevOps",
  "Open Source",
  "Linux",
  "Blockchain",
  "Internet of Things",
  "Embedded Systems",
  "Computer Vision",
  "Natural Language Processing",
  "AR/VR",
  "3D Printing",
  "UI/UX",
  "Product Management",
  "Competitive Programming",
  "Hackathon",

  // Career & Entrepreneurship
  "Career",
  "Career Development",
  "Entrepreneurship",
  "Startups",
  "Innovation",
  "Networking",
  "Internships",
  "Mentorship",
  "Leadership",
  "Project Management",
  "Business Development",
  "Personal Development",
  "Public Speaking",

  // Arts & Culture
  "Art",
  "Music",
  "Rock Music",
  "Metal Music",
  "Jazz",
  "Classical Music",
  "Folk Music",
  "Choir",
  "Instruments",
  "Guitar",
  "Piano",
  "Theater",
  "Cinema",
  "Film",
  "Photography",
  "Painting",
  "Drawing",
  "Sculpture",
  "Graphic Design",
  "Digital Art",
  "Dance",
  "Modern Dance",
  "Folk Dance",
  "Literature",
  "Poetry",
  "Creative Writing",
  "Fashion",
  "Design",

  // Sports & Fitness
  "Sports",
  "Football",
  "Basketball",
  "Volleyball",
  "Tennis",
  "Table Tennis",
  "Badminton",
  "Swimming",
  "Athletics",
  "Running",
  "Cycling",
  "Fitness",
  "Bodybuilding",
  "Yoga",
  "Pilates",
  "CrossFit",
  "Boxing",
  "Kickboxing",
  "Muay Thai",
  "Wrestling",
  "Judo",
  "Karate",
  "Taekwondo",
  "Martial Arts",
  "Archery",
  "Fencing",
  "Chess",
  "Climbing",
  "Mountaineering",
  "Hiking",
  "Camping",
  "Outdoor Sports",
  "Skiing",
  "Snowboarding",
  "Surfing",
  "Sailing",
  "Rowing",

  // Gaming & Entertainment
  "Gaming",
  "Video Games",
  "Esports",
  "Board Games",
  "Card Games",
  "Role-Playing Games",
  "Dungeons & Dragons",
  "Strategy Games",
  "Anime",
  "Manga",
  "Comics",
  "Cosplay",
  "Trivia",

  // Social & Community
  "Community",
  "Social Activities",
  "Volunteering",
  "Social Responsibility",
  "Charity",
  "Community Service",
  "Human Rights",
  "Animal Rights",
  "Animal Welfare",
  "Environmentalism",
  "Sustainability",
  "Climate",
  "Recycling",
  "Accessibility",
  "Education",
  "Peer Support",
  "Student Life",

  // Culture & Languages
  "Culture",
  "Languages",
  "English",
  "German",
  "French",
  "Spanish",
  "Italian",
  "Japanese",
  "Korean",
  "Chinese",
  "Arabic",
  "Russian",
  "Language Exchange",
  "International Students",
  "Cultural Exchange",
  "Travel",

  // Media & Communication
  "Media",
  "Journalism",
  "Communication",
  "Social Media",
  "Content Creation",
  "Podcasting",
  "Radio",
  "Television",
  "Video Production",
  "Filmmaking",
  "Editing",
  "Advertising",
  "Public Relations",

  // Debate & Politics
  "Debate",
  "Model United Nations",
  "Diplomacy",
  "Politics",
  "Geopolitics",
  "European Union",
  "International Affairs",
  "Public Policy",

  // Business & Finance
  "Business",
  "Economics",
  "Finance",
  "Investment",
  "Stock Market",
  "Trading",
  "FinTech",
  "Cryptocurrency",
  "Accounting",
  "Consulting",
  "E-Commerce",

  // Science & Research
  "Science",
  "Research",
  "Scientific Research",
  "Engineering",
  "Space",
  "Astronomy",
  "Aviation",
  "Aerospace",
  "Automotive",
  "Electric Vehicles",
  "Renewable Energy",

  // Food & Lifestyle
  "Food",
  "Cooking",
  "Coffee",
  "Tea",
  "Gastronomy",
  "Healthy Living",
  "Nutrition",
  "Lifestyle",

  // Events & Activities
  "Events",
  "Workshops",
  "Seminars",
  "Conferences",
  "Competitions",
  "Meetups",
  "Festivals",
  "Trips",
  "Networking Events",

  // Hobbies
  "Hobbies",
  "DIY",
  "Crafts",
  "Collecting",
  "Gardening",
  "Nature",
  "Animals",
  "Cars",
  "Motorcycles",
  "Aviation",
  "Travel",
];

const tags = [...new Set(tagNames)].map((tagName) => ({
  id: uuidv4(),
  tagName,
}));

await prisma.tag.createMany({
  data: tags,
});
